version: "3"

services:
  bnmoboxd-rest-db:
    image: postgres:13.4
    restart: always
    hostname: binotify-rest-db
    networks:
      - bnmoboxd-rest
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 5
    env_file: .env.production
    ports:
      - "8003:5432"
  bnmoboxd-rest-api:
    build: .
    hostname: bnmoboxd-rest
    container_name: bnmoboxd-rest
    restart: unless-stopped
    env_file:
      - .env.production
    networks:
      - bnmoboxd-rest
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/app/dist
    depends_on:
      bnmoboxd-rest-db:
        condition: service_healthy
  redis:
    image: "redis:latest"
    hostname: redis
    restart: always
    env_file: .env.production
    networks:
      - bnmoboxd-rest
    ports:
      - "6379:6379"

networks:
  bnmoboxd-rest:
